[workspace]
members = [
    "crates/dethrace-app",
    "crates/dethrace-core",
    "crates/dethrace-formats",
    "crates/dethrace-assets",
    "crates/dethrace-game",
    "crates/dethrace-ui",
    "crates/dethrace-audio",
    "crates/dethrace-tools",
]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.95"

[workspace.dependencies]
bevy = { version = "=0.19.1", default-features = false, features = ["2d"] }
